# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1dfc8f1ef83a4b4f0719e261fb99b62500b05daeb4a7220dfff3520e5526680feccd0e1d4ec0db04fdae3042d3aecb2cdd587075ba4c103428636829de0432da

test:
  secret_key_base: 6589b3b4c4dbd620378ce72269a56d1846b37d518df040812884dd1208ff97db71e811d82ad7aa233b5a79eb13d14a88a4c3f38c863d38d9f786c4b5561a0e7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
